### ISSUE TITLE
The "Join Group" AJAX command redirects that request to the "Accept Terms of Service" page

### ISSUE THREAD

**Issue by epaulson** [ofa/connect#8]
I'm not sure how to reproduce this, and it might have just been a temporary hiccup on the demo site, but after I logged in I was placed right in the 'Explore' section - but when I first tried to browse through the groups, clicking on 'Join Group' didn't do anything. 

Later, after I poked around into the 'My Profile' page, I hit the Connect ToS page, and after agreeing to them, I could join groups. 

I see that you've documented that you must agree to the ToS, but it'd be helpful to make sure that you get to the ToS page automatically before doing anything else - I didn't read the docs before trying to use the demo, so it wasn't clear to me what I was doing wrong.

**Comment by nickcatal** [comment]
Well this explains a lot.

It turns out the AJAX request that "Join Group" is sending to the server is being intercepted by the "Has this user accepted the terms of service? If not, forward them to the terms of service" middleware.

Thanks for the flag. I think the fix here is to just disable that middleware for AJAX requests (at least for now.)
